name: sprite
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bedtools=2.31.1
  - krbalancing=0.0.5
  - pairix=0.3.8
  - pip=24.3.1
  - pysam=0.22.1
  - python=3.12.8
  - pybedtools=0.10.0
  - gxx
  - pip:
      - spritefridge==1.4.0